server.port=4000
server.address=0.0.0.0
# ==============================
# 🔹 DATABASE CONNECTION (Supabase PostgreSQL)
# ==============================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.jsspurqzngsqgyqcotlq&password=fedepet1234.
#postgres://postgres.apbkobhfnmcqqzqeeqss:[YOUR-PASSWORD]@aws-0-[REGION].pooler.supabase.com:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# ==============================
# 🔹 JPA / HIBERNATE
# ==============================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# ==============================
# 🔹 LOGGING SQL (opcional)
# ==============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=60000
# ==============================
# 🔹 AWS
# ==============================
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=${AWS_BUCKET}
secret.key.jwt=${SECRET_KEY_JWT}
loggin.level.software.amazon.awssdk=DEBUG
# ==============================
# 🔹 GESTIONADOR DE TAMANO DE ARCHIVOS
# ==============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB